""" Módulo da clase Ui_infoWindow 
    Servirá para xerar unha ventana de info da app    

"""

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_ventana.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


""" módulos a importar """
from PySide2 import QtCore, QtGui, QtWidgets


class Ui_infoWindow(object):
    """ Clase para xerar unha ventana de información da aplicación
    """

    def setupUi(self, infoWindow):
        infoWindow.setObjectName("infoWindow")
        infoWindow.setFixedSize(460, 120)
        infoWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(infoWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.datosLabel = QtWidgets.QLabel(self.centralwidget)
        self.datosLabel.setGeometry(QtCore.QRect(40, 10, 391, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.datosLabel.setFont(font)
        self.datosLabel.setObjectName("datosLabel")
        infoWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(infoWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 459, 21))
        self.menubar.setObjectName("menubar")
        infoWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(infoWindow)
        self.statusbar.setObjectName("statusbar")
        infoWindow.setStatusBar(self.statusbar)

        self.retranslateUi(infoWindow)
        self.statusbar.messageChanged['QString'].connect(self.datosLabel.setText)
        QtCore.QMetaObject.connectSlotsByName(infoWindow)

    def retranslateUi(self, infoWindow):
        
        _translate = QtCore.QCoreApplication.translate
        infoWindow.setWindowTitle(_translate("infoWindow", "Sobre a aplicación"))
        self.datosLabel.setText(_translate("infoWindow", "CaLcULiÑa v1.0.0 Aplicación de calculadora para nen@s\n(c)2021 Miguel López Patricio Licencia GNU GPL"))
